services:
  app:
    image: serversideup/php:8.5-frankenphp
    container_name: laravel_app
    ports:
      - "8080:8080"
    volumes:
      - ../:/var/www/html
    environment:
      SSL_MODE: "off"
      CADDY_HTTP_PORT: "8080"
      CADDY_SERVER_ROOT: "/var/www/html/public"
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
    depends_on:
      - db
    user: "${UID}:${GID}"

  db:
    image: postgres:17
    container_name: laravel_db
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
